### ISSUE TITLE
Attempting to use to serve laravel - Receiving blank page , plus no info in logs

### ISSUE THREAD

**Issue by iannazzi** [mikechernev/dockerised-php#1]
@mikechernev 

I am trying to use this to serve laravel app...pretty close to working but need help on a few tweaks:

I placed your repository in a folder named `docker` within my root project folder. I mount the parent folder as a volume. Like so:

```
web:
    image: nginx:latest
    ports:
        - "8089:80"
    volumes:
        - ../:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ../:/code
```

Then I modify `site.conf` root to be `/code/public` which has `index.php` like so:

```
server {
    index index.php index.html;
    server_name php-docker.local;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /code/public;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

I am receiving a blank page when navigating to `php-docker.local:8089`. I have verified the basic configuration is working before attempting to serve the laravel project. 

I wanted to look at the access and error logs, but `cat access.log` leads me to a black hole. ls- l gives me

`
lrwxrwxrwx 1 root root 11 Apr  5 18:53 access.log -> /dev/stdout

lrwxrwxrwx 1 root root 11 Apr  5 18:53 error.log -> /dev/stderr
`
which look like sym links.... was there a trick to get the nginx log I am forgetting? Anything else you see wrong? 

Thanks for posting this, saw it in the docker email

**Comment by iannazzi** [comment]
Actually this is somewhat working, I can get some output of index.php, but then errors somewhere which I can't track down.

**Comment by mikechernev** [comment]
Hey @iannazzi,

The problem is that the `storage` directory of your Laravel application is not writable. You need to change its permissions to 777 and you should be able to get the Laravel starting screen (if this is a clean installation). 
It is quite interesting that you are trying to run a Laravel app inside Docker containers, because this will be the topic of my next blog post. But since it won't come out soon enough for you I will give you some additional info :wink: 
In order to run Laravel properly it requires a few PHP dependancies like OpenSSL, PDO, etc., which are not included in the default image. You can either create your own Docker build for those or you can use the one I have https://github.com/mikechernev/php7-fpm-laravel.
On top of that you need to add one more small change to the `site.conf` and add

```
    location / {
        try_files $uri /index.php?$args;
    }
```

Your final setup should look something like this:
**docker-compose.yml**

``` YAML
web:
    image: nginx:latest
    ports:
        - "8089:80"
    volumes:
        - ..:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: mikechernev/php7-fpm-laravel
    volumes:
        - ..:/code
```

**site.conf**

```
server {
    index index.php index.html;
    server_name php-docker.local;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /code/public;

    location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

As to why the PHP errors were not visible in the Docker Compose log - I guess it has something to do with the PHP image config. I will investigate further and see if there's anything that can be done about it.

In the meantime I will be happy to know if this solves your problem.

Cheers,
Mike

**Comment by iannazzi** [comment]
Just going to log some results...

First I updated `docker-compose.yml` to include a cool mysql container:

```
web:
    image: nginx:latest
    ports:
        - "8089:80"
    volumes:
        - ../:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: mikechernev/php7-fpm-laravel
    volumes:
        - ../:/code

angmysqldata:
    build: MysqlServer/data/.

angmysql:
    build: MysqlServer/.
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./MysqlServer/startup:/docker-entrypoint-initdb.d
    volumes_from:
      - angmysqld
```

then a few php artisan custom commands using the php container to get the database all set (would like to be able to have docker-compose run these artisan commands after creating the containers)

the result was a 500 error from the website php-docker.local/8089

went into the web container. Tried to look at `access.log` and `error.log` but they seem like symlinks to `/dev/stderr` so there is no output when `cat access.log` or `cat error.log`

Then I went into the php container, navigated to /code and ran `chmod -R 0777 storage`

This changed my error...  gave me a new error.. output in the browser.

```
ErrorException in Filesystem.php line 109:
file_put_contents(/code/storage/framework/views/17fad354bb10a1c112198c76509a661d9fd14c7c.php): failed to open stream: Permission denied
```

Went into the web container and ran  `chmod -R 0777 storage` at /code directory.

no change in the error. 

That is where I think I will end up tonight... almost totally awesome development setup. It still looks like I need to give someone write access to `/code/storage/framework/views/17fad354bb10a1c112198c76509a661d9fd14c7c.php`

Any more thoughts on the permissions?
