### ISSUE TITLE
php service should have depends_on web service

### ISSUE THREAD

**Issue by LongLiveCHIEF** [mikechernev/dockerised-php#13]
If the `web` service is started before the `php` service, You'll get an nginx error:

```
[emerg] 1:1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:12
```

Amending the config for `web` like so will correct this problem:

```yaml
web:
  # ... other configs
  depends_on:
    - php
```
