### ISSUE TITLE
Changing non-PHP files doesn't update the container volume

### ISSUE THREAD

**Issue by leocavalcante** [mikechernev/dockerised-php#6]
I added a simple .html file, but changing its content have no effect on the volume (I guess) I hit F5 on the browser and my changes doesm't  shows up. I only can see my changes when I rename the project folder (I guess it creates a new volume).

**Comment by leocavalcante** [comment]
Just realized that is a nginx issue. Did this simple example:

##### docker-compose.yaml
```yaml
version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "8080:80"
```

##### index.html
```
it works
```

Changed `it works` by `still working`, refreshed thr browser, still seeing `it works` :cry: 

Any tips on how to solve this?
